[package]
name = "nvide"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[features]
default = []
xtask = ["dep:nvide-rpc-schema", "nvide-rpc-schema/xtask"]

[dependencies]
nvide-rpc-schema = { path = "../nvide-rpc-schema", optional = true }
nvide-ui = { path = "../nvide-ui" }

[lints]
workspace = true
